server:
  port: 8080

spring:
  application:
    name: mcp-server
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

mcp:
  external-servers: ${MCP_EXTERNAL_SERVERS:}
  # 可以配置多个外部MCP服务器，用逗号分隔
  # 例如: https://external-mcp-server1.com,https://external-mcp-server2.com

logging:
  level:
    com.example.mcpserver: INFO
    org.springframework.ai: INFO